const FETCH_ALL = 'FETCH_ALL';
const FETCH_BY_ID = 'FETCH_BY_ID';
const LOADING_TRUE = 'LOADING_TRUE';
const LOADING_FALSE = 'LOADING_FALSE';
const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const LOG_OUT = 'LOG_OUT';
const ERROR = 'ERROR';
const CLEAR_ERROR = 'CLEAR_ERROR';
const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
const FETCH_USERS = 'FETCH_USERS';
const FETCH_MY_CARDS = 'FETCH_MY_CARDS';
const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
const CLEAR_FRIEND_STATUS = 'CLEAR_FRIEND_STATUS';

export {FETCH_ALL,FETCH_BY_ID,LOADING_TRUE,LOADING_FALSE,SIGN_UP,SIGN_IN,LOG_OUT,ERROR,CLEAR_ERROR,FETCH_ALL_USERS,FETCH_USERS,FETCH_MY_CARDS,CLEAR_SEARCH_RESULTS,CLEAR_FRIEND_STATUS};