const FETCH_ALL = 'FETCH_ALL';
const FETCH_BY_ID = 'FETCH_BY_ID';
const LOADING_TRUE = 'LOADING_TRUE';
const LOADING_FALSE = 'LOADING_FALSE';

export {FETCH_ALL,FETCH_BY_ID,LOADING_TRUE,LOADING_FALSE};