const FETCH_ALL = 'FETCH_ALL';
const FETCH_BY_ID = 'FETCH_BY_ID';
const LOADING_TRUE = 'LOADING_TRUE';
const LOADING_FALSE = 'LOADING_FALSE';
const SIGN_IN = 'SIGN_IN';
const SIGN_UP = 'SIGN_UP';
const LOG_OUT = 'LOG_OUT';

export {FETCH_ALL,FETCH_BY_ID,LOADING_TRUE,LOADING_FALSE,SIGN_UP,SIGN_IN,LOG_OUT};